### ISSUE TITLE
Release not found issue

### ISSUE THREAD

**Issue by arubalac** [ryandcarter/puppet-mule#7]
Hello,

I was trying to execute the command "puppet module install ryndcarter-mule" which i got from the forge site. When I executed the puppet command I am getting the below error. Could you please help me in resolving this issue.

<b>Error : </b> Could not find a release for this module (410 Gone)

Thanks & Regards
Arun

**Comment by ryandcarter** [comment]
Works for me. Seems you are missing an 'a':  "puppet module install ryndcarter-mule" should be: "puppet module install ryandcarter-mule"
